name: Bug Report
description: File a bug report
title: "[Bug]: "
# labels: ["bug-report", "CX"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug description
    attributes:
      label: Briefly describe the bug
      description: Enter a brief description about the bug report
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
  - type: textarea
    id: behaviour
    attributes:
      label: What is the expected behavior?
      description: Enter the expected behaviour of bug
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
  - type: textarea
    id: instructions
    attributes:
      label: Please provide step by step instructions on how to reproduce the bug
      description: Enter the description on how you plan to find the bug's solution
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
  - type: dropdown
    id: contribtype
    attributes:
      label: Contribution Event
      multiple: true
      options:
        - Community Exchange
        - GSSOC22
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD)
      options:
        - label: I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
          required: true
